### ISSUE TITLE
use fs.accessSync()

### ISSUE THREAD

**Issue by mattapperson** [tststs/atom-ternjs#13]
When using the latest build of Atom (0.1777) & atom-ternjs (0.4.9), I am getting:

atom-ternjs
fs.existsSync() is deprecated. Use fs.accessSync() instead.

**Comment by mattapperson** [comment]
Looks like this might be coming from Tern itself...

**Comment by tststs** [comment]
Hi @mattapperson,

i'm using <a href="https://github.com/atom/atom/blob/master/src/buffered-node-process.coffee"r>BufferNodeProcess</a> to spawn the tern server. <a href="https://github.com/atom/atom/blob/master/src/buffered-node-process.coffee"r>BufferNodeProcess</a> throws the deprecation. This will be fixed with atom 0.178 and up. should have no effect to the package, hopefully. :)

Thx for reporting!
tststs

**Comment by tststs** [comment]
fixed with release of 0.178
