### ISSUE TITLE
Top panel

### ISSUE THREAD

**Issue by MayhemYDG** [tststs/atom-ternjs#16]
![image](https://cloud.githubusercontent.com/assets/567105/6082048/5de76322-ae1e-11e4-9428-e9b59d1523a8.png)
This is driving me nuts.
- it's obscuring everything
- it's blocking mouse input
- it gets above what I'm actually writing when the editor is scrolled down

**Comment by tststs** [comment]
Should normally being displayed as a bottom panel, if your the cursor is located there. i'll check this.

Thx for reporting

**Comment by tststs** [comment]
is it still blocking everthing?

**Comment by tststs** [comment]
maybe it's the theme. which theme do you use?

**Comment by MayhemYDG** [comment]
One Dark.

**Comment by tststs** [comment]
Pls update to 0.4.12
I removed the modal for now and using a right panel, if there is not enough space at the bottom.
Tell me, if this is better.

**Comment by MayhemYDG** [comment]
Nah it's not, I use soft-wrapping so this can make the entire text jump up/down.
A simple floating box top-right would be fine. I wonder why you changed the previous bottom-right box too.

**Comment by tststs** [comment]
Cause there were other problems i faced.
I removed the modal, so there should be no blocking of the whole content anymore.

In the next release i will provide a option to optionally choose from panel or absolute positioned box (top-right, bottom-right).

**Comment by despairblue** [comment]
HAHA, I actually thought about open an issue because of the grey overlay. It just didn't bother me enough since I'm approaching a deadline atm. Then I updated atom-ternjs and this happened:
![screenshot from 2015-02-06 18 25 25](https://cloud.githubusercontent.com/assets/927609/6084002/9bf6ad80-ae2d-11e4-8d58-f3d2df6a9b65.png)
![screenshot from 2015-02-06 18 25 48](https://cloud.githubusercontent.com/assets/927609/6084004/9dec13be-ae2d-11e4-9e3d-e266a5fbd745.png)

With every letter I type the sidebar disappears for and instant and then reappears with another width. Don't want to complain here, actually I found that quite funny ^^

Just disabled `origin` and `url` for the time being.

How about using something like the linter package:
![screenshot from 2015-02-06 18 33 13](https://cloud.githubusercontent.com/assets/927609/6084118/a5269e14-ae2e-11e4-8cfe-fc12c6de29d2.png)

Just instead of following the cursor simply put it to the top or bottom. If that's what you tried before what problems did you face?

**Comment by MayhemYDG** [comment]
![poor paint job](https://cloud.githubusercontent.com/assets/567105/6084329/50b2a43e-ae30-11e4-8c13-88177e186784.png)
(excuse this quick paint job)
How about this? Less redundant text, closer to what we're currently looking at, not positioned somewhere unexpected.

**Comment by tststs** [comment]
yeah, the current setup fits perfectly into my needs. i never split the editor view and i'm working on 2560x1440. But i definitely see the problem now. i'll think about this and give it a update tomorrow.
Any input is welcome!

@despairblue i faced the problem, that sometimes the cursor was located behind the bottom-right box. could have just positioned the box to top then, haven't though about that.

@MayhemYDG thx! i will try some variations

**Comment by tststs** [comment]
Ok, i just couldn't find any better solution then the absolute positioned container.
I think there is just to much information to display and it won't work right at the cursor like the lint thing.
Positioning it right next to autocomplete-plus's suggestions is way to hard to handle. Check if there is enough space to the right, re-check the position of autocomplete-plus all the time a.s.o.

I added settings to disable the documentation-view, force it to be at the top/middle/bottom.
Should be ok for now.

If there are any problem, please open a issue! :)

Greetings from Berlin

**Comment by MayhemYDG** [comment]
>Positioning it right next to autocomplete-plus's suggestions is way to hard to handle.

Shouldn't it be possible with just html+css? Using flexbox to make sure the list/docs fill the available space, invert flex order when it needs to be displayed on the left instead of right for example.
Maybe you could ask the autocomplete-plus guys to add that kind of extensibility.

**Comment by MayhemYDG** [comment]
Also the new solution is better than the previous panels.

**Comment by MayhemYDG** [comment]
![image](https://cloud.githubusercontent.com/assets/567105/6092741/652b71ae-aeec-11e4-99db-2a4c77742d0d.png)
Looks easy enough, I've changed `atom-overlay`'s `display` to `flex`, and it looks like they could totally be next to each other.
