### ISSUE TITLE
Failed to find library ecma6.

### ISSUE THREAD

**Issue by MayhemYDG** [tststs/atom-ternjs#22]
![image](https://cloud.githubusercontent.com/assets/567105/6150116/ae7203b8-b20d-11e4-8938-916b4ac23edb.png)

**Comment by tststs** [comment]
es6 is currently not supported by tern.js out of the box. (as of my last information)
you may post some more information, so i can reproduce the error.

**Comment by MayhemYDG** [comment]
It does have an ecma6 library though: https://github.com/marijnh/tern/blob/master/defs/ecma6.json
It used to work yesterday.

```json
"libs": [
  "ecma5",
  "ecma6"
]
```

**Comment by tststs** [comment]
Ok, makes sense.
if it worked yesterday it is because i used to get tern via git://github.com/marijnh/tern.git in package.json.

From atom >= 0.178 there seems to be no way to publish a package with a url in package-dependencies. So, yesterday you had the latest commit of ternjs include. Now it just fetch the last release that is 0.8. Which sucks.

You may edit your atom-ternjs package.json to: and run apm install afterwards.

{
  "name": "atom-ternjs",
  "main": "./lib/atom-ternjs",
  "version": "0.4.17",
  "private": false,
  "description": "Javascript code intelligence for atom with tern.js. Uses suggestion provider by autocomplete-plus.",
  "activationCommands": {},
  "repository": "https://github.com/tststs/atom-ternjs",
  "license": "MIT",
  "engines": {
    "atom": ">0.176.0"
  },
  "dependencies": {
    "jquery": "*",
    "loophole": "*",
    "tern": "git://github.com/marijnh/tern.git",
    "atom-package-dependencies": "*"
  },
  "package-dependencies": {
    "autocomplete-plus": "*"
  },
  "providedServices": {
    "autocomplete.provider": {
      "versions": {
        "1.1.0": "provide"
      }
    }
  }
}

**Comment by despairblue** [comment]
Just for reference, tern is also looking for definition files in the project root folder, see http://ternjs.net/doc/manual.html#configuration. So one could actually add missing defs as well as custom defs on a project-by-project basis.

**Comment by tststs** [comment]
Good point.
For now we have to wait for apm to fix this issue <a href="https://github.com/atom/apm/issues/295">atom/apm/#295</a>  and get back to the latest version of ternjs.
