### ISSUE TITLE
Configure project view not shown correctly

### ISSUE THREAD

**Issue by faltfe** [tststs/atom-ternjs#277]
I've installed the latest Atom version (1.12.5) and the your package. But when I try to configure my project I get a broken view like in my screenshot.
![2016-11-23](https://cloud.githubusercontent.com/assets/13038138/20573257/3e760106-b1af-11e6-80e6-1e2d5381da67.png)
Sometime there aren't even a reaction when I click "Configure project". I can't scroll or close this broken view and have to restart the editor.

I work under Windows 10. There are no other plugins or themes installed right now.

**Comment by tststs** [comment]
The package only gets initialized if there is at least one pane with JS code active (see package.json for the activation hooks).
In the next release i will initialize the package if config view is triggered and the package isn't initialized at this time.

**Comment by faltfe** [comment]
If there is at least one javascript file open, it is working correctly.

**Comment by MaxMilton** [comment]
@tststs looking forward to the update. For every project I always forget to open a js file first and end up spending a bunch of time trying to work out what's wrong.

**Comment by janis-kra** [comment]
This also happens for me when I have a *.js file open, *but* I have a syntax highlighting / file type other than "JavaScript" selected. For example, my JS files with JSX in them have the "JavaScript (JSX)" style enabled:

![image](https://cloud.githubusercontent.com/assets/8240324/22293253/4451f896-e30f-11e6-9a65-d4be45e5c8ac.png)

If I understood @tststs correctly, then that will be fixed in the next release. But it seems that there is something off about your "detect whether a JS file is open" algorithm.

**Comment by tststs** [comment]
as of `v0.17.1` the plugin should be activated if configure is triggered.

@janis-kra i added `JavaScript (JSX)` to the supported grammars. you may give it another try. if its not working, feel free to create another issue.

Greetings
