### ISSUE TITLE
find-reference: display row:column instead of absolute character offset

### ISSUE THREAD

**Issue by tststs** [tststs/atom-ternjs#40]

**Comment by guymguym** [comment]
more ideas to make find refs a real swiss army knife:
1. Open the results in separate tab such as atom's Project Find Results to have more room.
2. Show the source line for context, with the reference itself highlighted inside.
3. Make the clickable area bigger (css block) instead of just the file name as a link which is currently very very small to click.
4. Add keyboard shortcuts to go to next/prev in reference list.

**Comment by tststs** [comment]
The commit does not include all your ideas.
Please open a separate issue for every enhancement. :)

tststs
