### ISSUE TITLE
How to complete function without parametrs?

### ISSUE THREAD

**Issue by vyusfire** [tststs/atom-ternjs#65]
Hi. How can i complete just function name, without parametrs between brackets?

**Comment by tststs** [comment]
Not possible right know.
You want to disable it completely or just in some cases?

Maybe at an option to the package, to disable the use of snippets?

**Comment by vyusfire** [comment]
> You want to disable it completely or just in some cases?

Yes, i wont to disabel.
> Maybe at an option to the package, to disable the use of snippets?

Maybe I misunderstood, but how will this help me?

**Comment by whitlockjc** [comment]
What happens now is if you ever accept a completion, you get the completed item's name, like `Promise` or `MyConstructor`, and its inferred arguments.  What @vyusfire is asking for is a way to get the completion of only the item's name without the arguments.  _(Correct me if I'm wrong)_

This has been bugging me too.  Imagine you have some constructor/function and it has functions/properties on it, if you accept the completion for said constructor/function, the completion assumes you want to call the function when you really wanted to just complete the name.

Here is an example: Let's say I want to type `Prom` in hopes of completing `Promise`.  When I accept the completion, instead of getting `Promise`, I get `Promise(executor: fn,resolve: fn(value: ?), reject: fn(reason: ?))`.  If my hopes was to end up typing `Promise.resolve()`, I now have to blow away everything within, and including, the parentheses and then type out `.resolve()`.

I think this is what @vyusfire is talking about.  If so, I don't think this assumptive completion is a Tern.js issue because Emacs doesn't have this problem when using its Tern.js integration.

**Comment by tststs** [comment]
No, it has nothing to do with tern. I just pass the argument list to the autocomplete-plus suggestion snippet field which makes use of the autocomplete-snippet package.

There are a few options:

* Add an option to completely disable the snippet behaviour.
* Add an additional shortcut to complete the function name without passing the snippet with arguments. So the user can make the decision if the snippets should be passed to the editor or just the function name. 

How do other editors behave?
What do you prefer and do you have other options as listed above?

**Comment by whitlockjc** [comment]
Emacs and Visual Studio Code both behave the same.  During the display of potential completions, they do show the parameter information and documentation but once you select one of the completions, just the completed item name itself is entered into the editor.  If you are completing a function, once you add the parentheses and are within the parentheses, both give you visual feedback about the function's arguments, types, etc.  Neither throw the parameters, or their suggestions, into the editor as part of the completion.

If I remember correctly, IntelliJ does the same type of thing as well.  That being said, I like the approach taken by the aforementioned editors/IDEs.

**Comment by tststs** [comment]
Hey there.

I added some options, so you guys can decide. Hope this helps.

options:

![bildschirmfoto 2015-05-16 um 22 46 42](https://cloud.githubusercontent.com/assets/3591665/7667906/b99c270a-fc1d-11e4-9f97-1c3ca2eca4ef.png)

both disabled:

![bildschirmfoto 2015-05-16 um 22 46 23](https://cloud.githubusercontent.com/assets/3591665/7667910/d00708fc-fc1d-11e4-839f-dae534a3dc02.png)

use snippets enabled:

![bildschirmfoto 2015-05-16 um 22 46 01](https://cloud.githubusercontent.com/assets/3591665/7667912/d981f3ec-fc1d-11e4-9c53-6b00ddd65bc5.png)

use both enabled:

![bildschirmfoto 2015-05-16 um 22 45 15](https://cloud.githubusercontent.com/assets/3591665/7667914/e3a195e4-fc1d-11e4-8dca-53b0a3210000.png)

**Comment by vyusfire** [comment]
Thank you so much! Works fine. Exactly what I wanted.

**Comment by tststs** [comment]
you're welcome :rocket:
