### ISSUE TITLE
tern exited with code: 1

### ISSUE THREAD

**Issue by Ventajou** [tststs/atom-ternjs#7]
Hi,

I'm trying to run this on Windows, the package installed just fine and I created a basic `.tern-project` file.

When I open a JS file, the following line shows up in the dev tools console:
`tern exited with code: 1      atom-ternjs-server.coffee:17`

**Comment by tststs** [comment]
Hey!

Windows was never reported, so i thought it works just fine.
Indeed the tern-server crashes right after opening the first js-file.

I will have a look at this and may come back to you, if i need some more information.

Thx for reporting.
tststs

**Comment by tststs** [comment]
Hey @Ventajou 

Could you please update the package and try again?
Please make sure, node is installed on your system and the PATH variable is set.
You may need to restart atom after the PATH variable was set.

I haven't had time to test absolute paths and just used relative path in my .tern.project on windows, so please open another ticket if that doesn't work.

Please also see the updated basic .tern-project located in the README. I removed all comments. This was a bit misleading and could crash the server because of malformed json.

Thx,
tststs

**Comment by Ventajou** [comment]
It works! I should have thought of the comments in the JSON...
Anyways, thanks for looking into this so quickly!
